# Generated by Django 4.0.4 on 2022-05-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('gpa', models.FloatField()),
                ('level', models.CharField(max_length=6)),
                ('gender', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=23)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
